# Generated by Django 5.1.4 on 2025-01-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='tip_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
