# Generated by Django 5.1.4 on 2025-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bill_due_date_bill_tip_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsplit',
            old_name='amount_owed',
            new_name='amount_spent',
        ),
        migrations.RemoveField(
            model_name='billsplit',
            name='user',
        ),
        migrations.AddField(
            model_name='billsplit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
