# Generated by Django 5.1.4 on 2025-01-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bill_tax_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsplit',
            old_name='name',
            new_name='participant_name',
        ),
    ]
