# Generated by Django 5.1.4 on 2025-01-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_billsplit_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsplit',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billsplit',
            name='participant_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
