# Generated by Django 5.1.4 on 2025-01-09 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bill_total_owed_bill_user_alter_bill_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_owed',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
