# Generated by Django 5.1.4 on 2025-01-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bill_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
